osx_image: xcode10
language: objective-c

cache: cocoapods
podfile: QHLazyTableImages/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    # - XCODE_PROJECT=core/QHLazyTableImages.xcodeproj
    - XCODE_WORKSPACE=Example/QHLazyTableImages.xcworkspace
    - DESTINATION="OS=12.0,name=iPhone Xs Max"
  matrix:
    - SCHEME="QHLazyTableImages"

before_install:
  # - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --pre --no-document --quiet
  - pod install --project-directory=Example

script:
  - set -o pipefail
#   - xcodebuild -project "$XCODE_PROJECT" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

# script:
#   - set -o pipefail
# - sh Startup.sh
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - pod lib lint --allow-warnings

after_success:
  - sleep 3
